version: '3.8'  

services:
  MariaDB_X:
    restart: always
    image: mariadb:11.6
    cap_add:
      - SYS_NICE
    ports:
      - 9306:3306
    volumes:
      - ${APP_DATA_DIR}/dbfile:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=ChangeMe
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
