version: "3.8"

services:
  rating-svm-web:
    image: pasmer/rating-svm-web:1.0.0
    container_name: rating-svm-web
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - umbrel_main_network
