version: "3.8"

services:
  rating-svm-web:
    image: pasmer/rating-svm-web:1.0.0
    container_name: rating-svm-web
    restart: unless-stopped
    networks:
      - umbrel_main_network
    # rimuovi l'esposizione diretta delle porte

  app_proxy:
    environment:
      APP_HOST: rating-svm-web
      APP_PORT: 8000

networks:
  umbrel_main_network:
    external: true
